### ISSUE TITLE
Import not found in the prebuild groovy script

### ISSUE THREAD

**Issue by royteeuwen** [alexcojocaru/elasticsearch-maven-plugin#113]
I copied the runforked-with-init to my own project and added the plugin the parent pom.xml, when trying to compile I get the following error (in java 11):

```
[INFO] --- maven-invoker-plugin:2.0.0:integration-test (integration-test) @ elasticsearch-service ---
[INFO] Building: midtier/pom.xml
[INFO] run script setup.groovy
[INFO] Running pre-build script: /Users/royteeuwen/Development/elasticsearch-service/target/it/midtier/setup.groovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/Users/royteeuwen/.m2/repository/org/codehaus/groovy/groovy/2.0.1/groovy-2.0.1.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] ..ERROR (1.0 s)
[INFO]   The pre-build script did not succeed. startup failed:
Script1.groovy: 1: unable to resolve class com.github.alexcojocaru.mojo.elasticsearch.v2.ItSetup
 @ line 1, column 1.
   import com.github.alexcojocaru.mojo.elasticsearch.v2.ItSetup
   ^
```

**Comment by alexcojocaru** [comment]
This looks like an IT misconfiguration to me.

That setup class is in the src/test dir, and the project build will include it in the test-jar artifact. Note that the pom.xml in each src/it directory contains a dependency on the test-jar, that should provide the ItSetup class.

If you cannot make it work, send me a zip of your project dir (after doing a `mvn clean` to get rid of the generated files) and I will look into it.

**Comment by royteeuwen** [comment]
I got it running by using the elasticsearch-maven-plugin inside the main project instead of making src/it folders. Then I use the failsafe plugin to run IT.java tests against the running index. Thanks!

Could you release 6.18 with java 11 support :) ?

**Comment by alexcojocaru** [comment]
I think you are doing it wrong.

Everything inside `src/it` is meant to be integration tests for the plugin itself (i.e. to verify that there are no bugs in it, at build time). Nothing in there is meant to be used outside this project.
The instructions in the README in the `Integration Tests` section are meant for contributors to this plugin project, so that they know how to write ITs for the plugin itself on making changes to it.

If you are writing integration tests for your own project, which uses Elasticsearch, all you have to do is to add the plugin dependency to your pom and configure it to start before the integration tests phase and stop after. Simple as that. There are no other files in this plugin project which you should use.

The fix I committed yesterday was only to the integration tests used by this project, you can see it by yourself here: https://github.com/alexcojocaru/elasticsearch-maven-plugin/commit/2289711cdcbc357eec71d9d900b72afe3aacc5e8 . These tests / files are not included in the maven plugin which you'd use, and hence there's no need to release a newer version.
The main src code, and the plugin, were already compatible with Java 11. If you are seeing other Java 11 compilation issues, let me know.

**Comment by royteeuwen** [comment]
That does explain it, thats indeed the way I had set it up now, wasn't clear out of the docs, might be my fault. Thanks!
