### ISSUE TITLE
Skip an execution 

### ISSUE THREAD

**Issue by UpeshAmin-TR** [alexcojocaru/elasticsearch-maven-plugin#15]
Is there any way that this plugin can support skipping the execution?  I'm thinking along the lines of something like in the snippet below.

```xml
<plugin>
    <groupId>com.github.alexcojocaru</groupId>
    <artifactId>elasticsearch-maven-plugin</artifactId>
    <version>2.0</version>
    <configuration>
        <clusterName>test</clusterName>
        <tcpPort>9300</tcpPort>
        <httpPort>9200</httpPort>
        <skip>${skip.elasticSearch}</skip>
    </configuration>
    <execution>
        ...
    </execution>
</plugin>
```

There doesn't seem to be anything that will allow this to skip.  It can be a part of the configuration for any execution as well.  Thank you.

**Comment by UpeshAmin-TR** [comment]
Any update on this please @alexcojocaru?

**Comment by alexcojocaru** [comment]
There is no support for skipping the execution for the time being. I will add that to the TODO list.
In the meanwhile, you can put the plugin config in a maven profile and enable/disable the profile as needed.
Or, if you are willing to add support for the "skip" property as a merge request, I won't mind.

**Comment by alexcojocaru** [comment]
I have been having issues with releasing the project - the project cannot be built locally due to a failure in one of the new tests. I have to find the root cause and fix it before releasing the plugin.

```testMojoExecutionIsSkipped(com.github.alexcojocaru.mojo.elasticsearch.LoadElasticsearchDataMojoTest)  Time elapsed: 10.35 sec  <<< FAILURE!
    junit.framework.AssertionFailedError
    	at junit.framework.Assert.fail(Assert.java:48)
    	at junit.framework.Assert.assertTrue(Assert.java:20)
    	at junit.framework.Assert.assertTrue(Assert.java:27)
    	at com.github.alexcojocaru.mojo.elasticsearch.LoadElasticsearchDataMojoTest.testMojoExecutionIsSkipped(LoadElasticsearchDataMojoTest.java:84```

**Comment by alexcojocaru** [comment]
Quick update: I found the root cause and I am working on fixing it and releasing the plugin. Stay tuned...

**Comment by alexcojocaru** [comment]
More details on the root cause: your machine and the build machine are probably slower than mine; on my machine, the delete request in tearDown didn't have enough time to execute before the node was stopped. Meaning that the 2nd test was creating the index, but the delete index request in the tearDown after the 2nd test didn't have enough time to execute on the server, before the 3rd test was executing. Hence the assert failure in the 3rd test.
I fixed that and I released a new version of the plugin - ie. 2.1. You can reference the new version in your pom file right away, but the search index at https://search.maven.org/ is going to take a couple of hours to update.

**Comment by UpeshAmin-TR** [comment]
@alexcojocaru - Thank you very much :+1:
