### ISSUE TITLE
Allow dots in field names (ES 2.4.x)

### ISSUE THREAD

**Issue by cartersm** [alexcojocaru/elasticsearch-maven-plugin#27]
Hi, 
I have a project that currently uses ES 1.7.5 and is targeting ES 2.4.x for an upgrade, and has dots in the names of some fields. These names must retain dots, as they come from/are used by other parts of a distributed system. 

ES <2.4 does not support dots in field names, but ES 2.4.x supports dots via a commandline option `-Dmapper.allow_dots_in_name=true` (See [the ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html)). This issue is to request support for `mapper.allow_dots_in_name` via the config for this plugin, so that we can set the option in our integration tests automatically. 

I have tried setting the option via `maven-failsafe-plugin`, both as a system property and as part of the `argLine` options, to no avail, but the option flag can be added to a `mvn verify` command: `mvn verify -Dmapper.allow_dots_in_name=true`.

**Comment by alexcojocaru** [comment]
Sure, I can add support for that in the near future.
It looks like you need that option with ES v2.x, meaning I will add support for it in the 2.x branch and then to master (which works with ES 5 and above).

**Comment by cartersm** [comment]
Alright, sounds good to me. Thanks!
Just to confirm: are the 5.x releases compatible with ES 2.x?

**Comment by alexcojocaru** [comment]
No, it is not.

**Comment by alexcojocaru** [comment]
I got this to work without any code changes. You can use the org.codehaus.mojo:properties-maven-plugin to set the system property on the main JVM, before starting ES. It works because ES instance starts in the main JVM and not in a forked one.

See these gists for a complete reference:

pom.xml
https://gist.github.com/alexcojocaru/315f9a575b9139338ae3676b227b6b29

elasticsearch.script
https://gist.github.com/alexcojocaru/8904bc6d484d80b1c53d8397f2086f63

**Comment by cartersm** [comment]
Ah, beautiful! That's what I couldn't find, I guess.
