### ISSUE TITLE
Allow to redirect log to file  

### ISSUE THREAD

**Issue by aakhmerov** [alexcojocaru/elasticsearch-maven-plugin#35]
* given
  * I run forked plugin execution
* when
  * I specify log path parameter 
* then 
  * com.github.alexcojocaru.mojo.elasticsearch.v2.AbstractElasticsearchBaseMojo#getLog is returning file based logger 

Right now plugin is always writing to the console log, would be nice to configure it somehow.

**Comment by alexcojocaru** [comment]
The plugin already supports configuring the logging done by the ES - that's the log most users will be interested in.
As for the plugin itself, personally I don't think it should have the option to log to a file; I don't see much benefit in doing that, and I cannot recall seeing anything similar on any other plugin to make me believe it would be a useful feature.

**Comment by aakhmerov** [comment]
Hi @alexcojocaru,

thanks for your answer. Let me add a bit of context here. If I am running a build process right now, the cluster is getting instantiated somewhat close to 

`
ClusterConfiguration.Builder clusterConfigBuilder = new ClusterConfiguration.Builder()
                .withArtifactResolver(buildArtifactResolver())
                .withLog(getLog());
`

where `getLog()` method returns maven console log as I understand. Which means that ES log will be part of my main build process log. Which is confusing for me and I would like to get rid of it. Is it configurable somehow right now?

Cheers,
Askar

**Comment by aakhmerov** [comment]
@alexcojocaru , ping. Any reaction here? Should I prepare pull request or we don't have agreement of feature request yet? 

Cheers,
Askar

**Comment by alexcojocaru** [comment]
Sorry about the long delay in replying.

The console log created with `new DefaultLog(new ConsoleLogger(getMavenLogLevel(), "console"))` is only used for the logging done by the plugin itself.

The ES instance(s) have their own logging mechanism and configuration - by default, the log files are under target/elasticsearch/logs.
Example: run the plugin build `mvn clean verify` and then look under `target/it`; there is a directory for each integration test case and, for each test case, there is `target/elasticsearch0` where the elasticsearch instance is installed; under that, there's the `logs` directory.

The `pathLogs` plugin parameter hasn't been implemented yet - it's supposed to be passed to Elasticsearch as `path.logs`, in order to tell ES to put the log files into a custom directory (see https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html for details). Same for `pathData`.

**Comment by alexcojocaru** [comment]
Closing this, since I believe my comment above addresses the issue, and there have not been new comments in the past 2 months.
