### ISSUE TITLE
autoCreateIndex default value out of sync with readme

### ISSUE THREAD

**Issue by torgeir** [alexcojocaru/elasticsearch-maven-plugin#38]
The [`defaultValue` of `autoCreateIndex`](https://github.com/alexcojocaru/elasticsearch-maven-plugin/blob/4470c10a9954272cd79724abe87d989efea86470/src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/AbstractElasticsearchMojo.java#L129) is out of sync with [the readme](https://github.com/alexcojocaru/elasticsearch-maven-plugin/blame/d03b905310ad198260cf1e1e6241dedb8e265201/README.md#L62)

It seems I need `<autoCreateIndex>true</autoCreateIndex>` for the initial bulk insert to work for indices that use template mappings

Edit: Here's a pr to fix it https://github.com/alexcojocaru/elasticsearch-maven-plugin/pull/39.

**Comment by dadoonet** [comment]
I agree. I wonder actually why it's false by default. My gut feeling is that we should fix the code, not the doc.

**Comment by torgeir** [comment]
Updated to change the default value in `AbstractElasticsearchMojo` instead #39

**Comment by alexcojocaru** [comment]
The doc is wrong. The default value is meant to be `false`; DefaultsTest.testAutoCreateIndex() verifies that.
I am going to update the doc, unless you have a strong argument for updating the doc and allowing ES to auto create indexes by default.

**Comment by dadoonet** [comment]
@alexcojocaru Allowing creating automatically indices is the default behavior of elasticsearch. Why changing this default?

It actually has a consequence any time you would like to run your tests with x-pack plugin. X-Pack creates indices automatically (monitoring, ML, watcher...).

**Comment by torgeir** [comment]
It being ES default behaviour ought to be strong enough an argument, don't you think? 

I was kind of stumped by this my self, as all of our otherwise working code that were creating indices in ES, e.g. using template mappings, was failing only in our tests after attempting to use this plugin

**Comment by alexcojocaru** [comment]
Personally, I believe allowing indexes to be created automatically is potentially a security issue, a source of confusion and a source of bugs. That said, I agree with following the ES default behavior.

If you are willing to update the changeset to fix the integration tests in addition to making the source code changes (ie. move the content of AutoCreateIndexTest.testAutoCreateIndex into DefaultsTest.testAutoCreateIndex and vice-versa, set es.autoCreateIndex to false in src/it/runforked-auto-create-index-true/setup.groovy and rename src/it/runforked-auto-create-index-true to src/it/runforked-auto-create-index-false), that would be best.
Otherwise, you will have to wait a week or two for me to fix that.

**Comment by alexcojocaru** [comment]
Fixed in https://github.com/alexcojocaru/elasticsearch-maven-plugin/commit/401e153e97d9098942a5ffc212cd633d4d639fe9
