### ISSUE TITLE
Upgrade to ElasticSearch 2.0

### ISSUE THREAD

**Issue by gunnarmorling** [alexcojocaru/elasticsearch-maven-plugin#5]
It'd be awesome if the plug-in was upgraded to ES 2.0. Thanks btw. for providing this useful utility.

**Comment by alexcojocaru** [comment]
I will try to get that done in the next couple of days.

**Comment by alexcojocaru** [comment]
I updated the plugin to work with ES 2.0.0. Because of that, I changed the plugin version to 2.0 - the README.md file has been updated accordingly.
The new plugin has just been released to the Maven central repository. It will take a few hours until it shows up in searches.
Let me know if the new plugin does not work as expected.

**Comment by gunnarmorling** [comment]
Thanks, @alexcojocaru, works like a charm!

A bit off-topic, but I see random names (different with each run) written by ES in the beginning of log lines in the console, e.g. like this:

    [INFO] [Lorelei II] version[2.0.0], pid[37939], build[de54438/2015-10-22T08:09:48Z]
    [INFO] [Lorelei II] initializing ...
    ...

I would have expected the cluster name I configured instead. Do you happen to know how I can avoid the random names there?

**Comment by alexcojocaru** [comment]
The plugin config allows you to set a cluster name. But the node name(s) are not set by the plugin, meaning they will be randomly chosen. See https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html : "You may also want to change the default node name for each node to something like the display hostname. By default Elasticsearch will randomly pick a Marvel character name from a list of around 3000 names when your node starts up.".
The cluster name is a required property, in order to be able to tell other [master, data or client] nodes how connect to it. But the node name(s) is not that important in my mind, at least in this context.

**Comment by gunnarmorling** [comment]
I see; Many thanks for the explanation. The random names confused me a bit, but as you say it's probably not necessary to configure them through the plug-in.
