### ISSUE TITLE
Init script has not very convinient format.

### ISSUE THREAD

**Issue by alex-semenyuk** [alexcojocaru/elasticsearch-maven-plugin#63]
Init script has not very convinient format. I mean, that for now, it is parsed right if a command is in one line, which is not very convinient when you have big mapping or record. Do you plan to make it more convinient?  

Thanks.

**Comment by alexcojocaru** [comment]
Each line in the init script should have 2 or 3 parts; the first one is very short and readable, the second one is relatively short and also readable, while the third part (the JSON) can be very long and not readable the way its' formatted. I have had no problems taking the JSON from there and formatting it using a JSON formatting tool.
Since the init script is to help create seed data in ES, it is not supposed to be touched often.

Since this is the first request for better formatting of the init script, I am going to put it on hold until there will be several more upvotes for this.

**Comment by alexcojocaru** [comment]
Forgot to mention that contributions are very welcome.

**Comment by alexcojocaru** [comment]
It's done. I have added support for JSON format in the init file.
