### ISSUE TITLE
Run with local version of elastic

### ISSUE THREAD

**Issue by naveenkumaran** [alexcojocaru/elasticsearch-maven-plugin#87]
I have a local version of elastic search zip in my build directory. is there a possibility to skip the download and use the local version

**Comment by alexcojocaru** [comment]
I would like to know what the reason behind your ask is.
If it's just to work in offline mode, or to avoid downloading the same artifact repeatedly, then the plugin takes care of that already. It uses the local m2 repository as a cache; first, it looks for the required artifact (eg. elasticsearch-oss-6.3.0.zip) in the corresponding m2 subdirectoy (eg. /home/x/.m2/repository/com/github/alexcojocaru/elasticsearch-oss/6.3.0/elasticsearch-oss-6.3.0.zip). If it's there, it uses that artifact without hitting the remote, otherwise it downloads the artifact from the remote into the m2 subdirectory (for subsequent use) and uses it.
If you are asking because you want to use a custom ES artifact, then you can trick the plugin into using the local file using the `downloadUrl` param. Just make sure to specify a non-existing ES version (eg. 6.100.0), to force the execution of the `downloadUrl` related logic (otherwise it will get the artifact from the m2 cache if it's there), eg:
```
        <plugin>
            <groupId>com.github.alexcojocaru</groupId>
            <artifactId>elasticsearch-maven-plugin</artifactId>
            <version>6.13</version>
            <configuration>
                <version>6.100.0</version>
                <clusterName>test</clusterName>
                <downloadUrl>file:///home/alex/.m2/repository/com/github/alexcojocaru/elasticsearch-oss/6.3.0/elasticsearch-oss-6.3.0.zip</downloadUrl>
            </configuration>
            <executions>
            ....
            </executions>
        </plugin>
```

**Comment by naveenkumaran** [comment]
We would like to run the IT test in Jenkins, the server does not have access to Internet. It can only download artifacts from our local Nexus

**Comment by naveenkumaran** [comment]
Hi Alex,
Many thanks for the reply.

We would like to run the IT test in Jenkins, the server does not have
access to Internet. It can only download artifacts from our local Nexus

**Comment by alexcojocaru** [comment]
Got it. I asked that so I know which answer applies to your use case.
Try the 2nd approach, using the *downloadUrl* override; I tested it yesterday and it worked for me but, if it doesn't work as expected, please reopen this issue.

**Comment by naveenkumaran** [comment]
It works as suggested by you. Many thanks
