### ISSUE TITLE
Allow to add plug-ins as Maven dependency

### ISSUE THREAD

**Issue by gunnarmorling** [alexcojocaru/elasticsearch-maven-plugin#9]
I would like to add plug-ins obtainable via Maven to the bootstrapped ES instance. Unless there is already a convinient way for doing this, I am proposing to add support for it like so:

```
<plugin>
    <groupId>com.github.alexcojocaru</groupId>
    <artifactId>elasticsearch-maven-plugin</artifactId>
    <version>2.0</version>
    <configuration>
        <clusterName>hsearch-es-test-cluster</clusterName>
        <tcpPort>9300</tcpPort>
        <httpPort>9200</httpPort>
        <pluginsPath>${project.build.directory}/_ES_PLUGINS_</pluginsPath>

        <!-- Obtains plug-in ZIPs given via Maven group + artifact id -->
        <pluginArtifacts>
            <pluginArtifact>org.elasticsearch.plugin:delete-by-query:2.0.0</pluginArtifact>
            <pluginArtifact>org.elasticsearch.plugin:analyzer-icu:2.0.0</pluginArtifact>
            ...
        </pluginArtifacts>
    </configuration>
    <executions>
        ...
    </executions>
</plugin>
```

If you like the idea in general, I could try and help out with implementing it. WDYT?

**Comment by alexcojocaru** [comment]
I added support for the **pluginsPath** option because I had an ES plugin already in my maven project, somewhere under src, which was copied to target by the maven resource plugin, and using that option I was able to tell the ES node to use that directory under target as plugins directory.
I admin it's not the most flexible or elegant solution :)

What you proposed is an interesting idea and I like it. Just a couple of questions:
* How are you planning to download the artifacts from the maven central repo? using the HttpClient? it would be nice to use maven for that, but I cannot see how that could be done;
* If an artifact is not in the maven central repo, will it still be possible to provide the [direct] url to it? maybe just adding the *mvn* directive to the artifacts in the maven repo would suffice for now (eg. *mvn:org.elasticsearch.plugin:delete-by-query:2.0.0*); later on it would be possible to add support for other directives such as *url*

alex

**Comment by gunnarmorling** [comment]
Cool, clad to hear you like the idea :)

> How are you planning to download the artifacts from the maven central repo? using the HttpClient? it would be nice to use maven for that, but I cannot see how that could be done;

One can use the Maven resolver to do this job. This would also take care of repo settings e.g. in settings.xml etc. I don't have an example at my hands right now, but it should be not too hard.

> If an artifact is not in the maven central repo, will it still be possible to provide the [direct] url to it? 

Yes, as you say I'd only support Maven artifacts for now (because that's what I'd need atm. ;). But one could provide other means in the future, either through that prefix approach or via othe XML elements maybe.

I will try and provide a fix for this during the next days. I'll report back how it goes :)

**Comment by alexcojocaru** [comment]
Thank you.
As I said in my previous comment, please add the *mvn* prefix for now to all such artifacts; it will make it easier in the future to add support for other "protocols".

alex

**Comment by angelcervera** [comment]
Is this feature in the last release?

**Comment by alexcojocaru** [comment]
No it is not. I have no plans to add support for ES plugins myself, but contributions are always welcome.

**Comment by statut** [comment]
@alexcojocaru could you, please, tell me, how I can add supporting of modules? I need org.elasticsearch.module:lang-expression module for integration tests.

**Comment by alexcojocaru** [comment]
There is no support for modules in the current ES maven plugin. Nor am I planning on adding it myself, for I am working on rewriting the plugin to work with ES 5.

**Comment by jomarl** [comment]
Is there any way to load plugins using the standard plugin manager after starting an instance? For example I want to install the analysis-phonetic plugin in the simplest possible way, e.g. by /bin/plugin install <pluginName>. I can probably do this with a separate maven exec step, but as the thread-starter pointed out some support for automatically loading plugins would be convenient.

**Comment by alexcojocaru** [comment]
As far as I can tell, that is the correct way to add plugins to the instance: using the elasticsearch-plugin utility. It would be nice to enable the `--batch` flag on the utility (https://www.elastic.co/guide/en/elasticsearch/plugins/current/_other_command_line_parameters.html#_batch_mode), and add support for custom `ES_JAVA_OPTS` (https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-management-custom-url.html).
Does the plugin utility have to run after the ES instance has started, or before?
When running multiple ES instances, do the plugin have to be installed in each instance? Or is it sufficient to install them in one of the instances, and then they will be propagated across the cluster?

**Comment by jomarl** [comment]
The plugins have to be installed before instance startup for them to be properly loaded. If the plugin uses the same base installation to start several instances it would only be necessary to install them once as long as each instance is configured using the same plugin directory.

Off the top of my head I cannot think of any normal use-cases were you would like to run instances with different plugins installed, but allowing different plugins/versions for each instance would of course ensure that any special needs are supported.

A minor drawback compared to loading plugins using maven artifacts is that the installation could be a bit slower as any local or company wide artifact cache cannot be leveraged

**Comment by alexcojocaru** [comment]
Thanks for the clarifications.

The ES maven plugin can be configured to start multiple instances; each has it's own directory layout and they don't share anything in terms of file system.

If the ES can be configured with a custom plugins directory (I haven't found such option for ES 5), then the plugins can be installed once into the shared directory. Otherwise the plugin would have to install the plugins for each instance individually.

Using a maven based plugin could be done (assuming the ES maven plugin has plugin support) through a hack:
* download the artifact ahead of time (https://maven.apache.org/plugins/maven-dependency-plugin/get-mojo.html)
* point to the plugin installer to the maven artifact (https://www.elastic.co/guide/en/elasticsearch/plugins/5.2/plugin-management-custom-url.html)
That could be automated by using the maven:// protocol and let the ES maven plugin do the download (not difficult, for it already knows how to download the ES artifact) and the pass a file:// location to the plugin installer

**Comment by alexcojocaru** [comment]
Finally, this feature request is getting somewhere:
I added support for installing plugins: https://github.com/alexcojocaru/elasticsearch-maven-plugin/tree/es5-plugins. It is incomplete for the time being (I haven't done any testing on installing via URL, nor have I written tests around the new code). The plan is to finalize this in the next few days.

**Comment by alexcojocaru** [comment]
The feature branch has been merged into master.

In regard to using Elasticsearch plugins distributed as maven artifacts: that option is not available in Elasticsearch 5+ any longer, from what I can tell. If anyone can show me otherwise, I can look into adding support for that - it should be relatively straightforward.

**Comment by jomarl** [comment]
After incorporating the latest version of the plugin in our project as a replacement for an existing ant-based nightmare I noticed that the plugin fails my windows 10 based laptop.

> .\bin\elasticsearch-plugin" install --batch analysis-phonetic' is not recognized as an internal or external command, operable program or batch file.
> ..
> ..
> [ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:5.6:runforked (start-elasticsearch) on project xxx: Elasticsearch [0]: Cannot execute command '[cmd, "/c .\bin\elasticsearch-plugin", install, --batch, analysis-phonetic]' in directory 

Seems like commons exec somehow screws up the command quoting.

Changing
`         cmd = new CommandLine("cmd").addArgument(String.format("/c %s", windowsExecutable));
`
to 
`            cmd = new CommandLine("cmd")
                    .addArgument("/c")
                    .addArgument(windowsExecutable)`
seems to do the trick for me.

On my linux based workstation it works like a charm. :+1: for implementing this feature.

**Comment by alexcojocaru** [comment]
Thanks for the bug report. I am going to set up a Windows VM to test the plugin on Windows - the testing and bug fixing should not take long.

**Comment by alexcojocaru** [comment]
Tested and fixed the issues on Windows around starting a new process. A new version (5.7) has been released.
