### ISSUE TITLE
How can I specify jvm properties?

### ISSUE THREAD

**Issue by snuyanzin** [alexcojocaru/elasticsearch-maven-plugin#93]
I want to add some more jvm properties which are not in `jvm.options`. Is there a way to do it without any additional plugins?

**Comment by alexcojocaru** [comment]
I would use the *pathConf* property on the plugin to tell the ES instance to use a custom directory as its config dir. There is a caveat though: make sure this custom directory also contains the rest of the files in $ES_HOME/config (ie. *elasticsearch.yml* and *log4j2.properties*), otherwise you'll get unexpected behavior. 
Does that help?

**Comment by snuyanzin** [comment]
Yes, it works.
Thank you
